[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    "contracts/pair_concentrated",
    "contracts/pair_transmuter",
    #  "contracts/pair_concentrated_inj", TODO: rewrite OB liquidity deployment
    "contracts/pair_grid_xgrid",
    "contracts/pair_xyk_sale_tax",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    #  "contracts/cw20_ics20", # contract is being deprecated
    "templates/*",
    "contracts/tokenomics/*",
    "contracts/periphery/*",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true

[patch.'https://github.com/fanfury-sports/gridiron-core']
gridiron = { path = "packages/gridiron" }

[patch.crates-io]
cw-multi-test = { git = "https://github.com/gridiron-fi/cw-multi-test.git", rev = "269a2c829d1ad25d67caa4600f72d2a21fb8fdeb" }
